"use client";

import { useState } from "react";
import { lookupWord } from "@/lib/api/dictionary";
import { VocabularyCard } from "@/components/ui/vocabulary-card";

const CEFR_LEVELS = ["A1", "A2", "B1", "B2", "C1", "C2"] as const;

export default function DictionaryPage() {
    const [word, setWord] = useState("");
    const [level, setLevel] = useState<(typeof CEFR_LEVELS)[number]>("A1");
    const [searchedWord, setSearchedWord] = useState("");
    const [searchedLevel, setSearchedLevel] = useState<(typeof CEFR_LEVELS)[number]>("A1");
    const [hasSearched, setHasSearched] = useState(false);
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    async function handleLookup() {
        const normalizedWord = word.trim();

        if (!normalizedWord) {
            setHasSearched(true);
            setError("Please enter a word to look up.");
            setSearchedWord("");
            return;
        }

        setIsLoading(true);
        setError(null);
        setHasSearched(true);

        const result = await lookupWord(normalizedWord, level);

        if (result.error || !result.data) {
            setError(result.error || "Unable to fetch dictionary data.");
            setSearchedWord("");
            setIsLoading(false);
            return;
        }

        setSearchedWord(result.data.word || normalizedWord);
        setSearchedLevel(level);
        setIsLoading(false);
    }

    return (
        <div className="max-w-4xl mx-auto px-4 py-8">
            <div className="bg-gradient-to-r from-[#2D6BEB] via-[#2E8BFF] to-[#33A6FF] rounded-3xl p-6 md:p-8 text-white shadow-xl mb-6">
                <p className="text-xs font-bold tracking-[0.2em] uppercase text-white/80">Smart Dictionary AI</p>
                <h1 className="text-3xl md:text-4xl font-black mt-2 mb-2">Look up words by your level</h1>
                <p className="text-white/90 max-w-2xl">
                    Get CEFR-tailored meanings, IPA pronunciation, examples, and synonyms generated by AI.
                </p>
            </div>

            <div className="bg-white dark:bg-[#1B1D24] border border-[#D4D6DB] dark:border-[#2E3039] rounded-2xl p-5 md:p-6 mb-6">
                <div className="grid grid-cols-1 md:grid-cols-[1fr_auto_auto] gap-3 items-end">
                    <div>
                        <label className="block text-sm font-semibold text-[#1A1C1E] dark:text-white mb-2">Search Word</label>
                        <input
                            type="text"
                            value={word}
                            onChange={(e) => setWord(e.target.value)}
                            onKeyDown={(e) => {
                                if (e.key === "Enter") {
                                    handleLookup();
                                }
                            }}
                            placeholder="Type a word in English or Vietnamese (e.g. curious, tò mò)"
                            className="w-full h-12 px-4 rounded-xl border border-[#D4D6DB] dark:border-[#2E3039] bg-white dark:bg-[#0F1729] text-[#1A1C1E] dark:text-white focus:outline-none focus:ring-2 focus:ring-[#3C83F6]"
                        />
                    </div>

                    <div>
                        <label htmlFor="dictionary-cefr-level" className="block text-sm font-semibold text-[#1A1C1E] dark:text-white mb-2">CEFR Level</label>
                        <select
                            id="dictionary-cefr-level"
                            title="Select CEFR level"
                            value={level}
                            onChange={(e) => setLevel(e.target.value as (typeof CEFR_LEVELS)[number])}
                            className="h-12 min-w-24 px-3 rounded-xl border border-[#D4D6DB] dark:border-[#2E3039] bg-white dark:bg-[#0F1729] text-[#1A1C1E] dark:text-white focus:outline-none focus:ring-2 focus:ring-[#3C83F6]"
                        >
                            {CEFR_LEVELS.map((cefrLevel) => (
                                <option key={cefrLevel} value={cefrLevel}>
                                    {cefrLevel}
                                </option>
                            ))}
                        </select>
                    </div>

                    <button
                        onClick={handleLookup}
                        disabled={isLoading}
                        className="h-12 px-6 rounded-xl font-semibold bg-[#3C83F6] text-white hover:bg-[#2B6FE0] disabled:opacity-70 disabled:cursor-not-allowed transition-colors"
                    >
                        {isLoading ? "Looking up..." : "Lookup"}
                    </button>
                </div>
            </div>

            {!hasSearched && (
                <div className="bg-[#F0F2F5] dark:bg-[#151A28] border border-dashed border-[#C6CBD5] dark:border-[#2E3039] rounded-2xl p-8 text-center">
                    <div className="text-4xl mb-2">📘</div>
                    <h2 className="text-lg font-bold text-[#1A1C1E] dark:text-white mb-1">Ready to explore vocabulary</h2>
                    <p className="text-[#75777F]">Enter a word, choose your CEFR level, and press Lookup.</p>
                </div>
            )}

            {hasSearched && error && (
                <div className="bg-white dark:bg-[#1B1D24] border border-red-300 dark:border-red-800 rounded-2xl p-6">
                    <p className="font-semibold text-red-600 dark:text-red-400 mb-1">Lookup failed</p>
                    <p className="text-sm text-red-500 dark:text-red-300">{error}</p>
                </div>
            )}

            {hasSearched && !error && searchedWord && (
                <VocabularyCard word={searchedWord} userLevel={searchedLevel} />
            )}
        </div>
    );
}
